### ISSUE TITLE
Cannot start the GUI

### ISSUE THREAD

**Issue by CsatiZoltan** [TheRaytracers/freecad-povray-render#4]
When I click on the camera icon to start the GUI, I get the following error:
```
12:04:08  Running the Python command 'Export' failed:
Traceback (most recent call last):
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/ExportCommand.py", line 41, in Activated
    dialog = Dialog()
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 47, in __init__
    self.initUI()
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 57, in initUI
    self.textureTab = TextureTab()
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 581, in __init__
    self.initUIElements()
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 592, in initUIElements
    self.addObjectsTexturesLists()  # add the two lists at the top
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 617, in addObjectsTexturesLists
    self.addTextureList()
  File "/home/zoltan/.FreeCAD/Mod/POV-Ray-Rendering/Dialog.py", line 665, in addTextureList
    categories = predefined.getchildren()

'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```
The FreeCAD version I use is
```
OS: Ubuntu 18.04.6 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```
Do you have any ideas what the problem could be?

**Comment by CsatiZoltan** [comment]
Now I see the same problem reported on https://forum.freecadweb.org/viewtopic.php?f=9&t=48629&start=40#p532403

**Comment by TheRaytracers** [comment]
Thank you a lot for your bug report!
It should be fixed now. Just update the workbench via the addon manager to get the most recent version.

I would be happy if you could write briefly if it works now, because I could not reproduce the error (probably because of my python version) :)

**Comment by CsatiZoltan** [comment]
Great, it works now. I could produce my first image!

By the way, I use the precompiled (AppImage) FreeCAD, which comes with Python 3.9 -- that is why I came across this bug.
